### PR TITLE
Add policy document for using GitHub actions in workflows

### LINKED ISSUE #12: Create a document which describes the policy on the use of GitHub actions
There are many actions but which ones should be trusted from a supply chain security POV?

There is also the issue of whether to refer to an action version by SHA or mutable tags. SHA is considered more reliable and repeatable as tags can and do move.

Finally, we should enable dependabot to keep the actions up to date.

### PR DESCRIPTION
**Pull request by bjhargrave**
Closes https://github.com/instructlab/dev-docs/issues/12

### CODE REVIEW

**Review by nathan-weinberg — APPROVED** [review]
LGTM, would like @russellb to review before we merge

**Review by mrutkows — CHANGES_REQUESTED** [review]
Not intending to impede approval/merge; just wanted to raise questions I had.  I am truthfully very interested in these requirements as I had plans to explore bringing in other actions for security-related purposes over time.

**Review by jjasghar — CHANGES_REQUESTED** [review]
I think we should have conversation about some of the logistics of this before we merge.

**Comment by russellb** [comment]
@bjhargrave This PR will probably have to be re-posted from a public fork. Apologies for the disruption.

**Comment by bjhargrave** [comment]
Replaced by https://github.com/instructlab/dev-docs/pull/45

**Pull request closed without merging**
