### PR TITLE
Propose simplifications to the SDG API design

### PR DESCRIPTION
**Pull request by markmc**
See instructlab/sdg#61 for some of the discussion on this, but I've tried to summarize those discussions in the design doc.

### CODE REVIEW

**Review by russellb — APPROVED** [review]
This all sounds great to me. Thank you!

**Review by hickeyma — APPROVED** [review]

**Comment by hickeyma** [comment]
The direction of the proposal makes sense.

**Comment by markmc** [comment]
There are 3 small changes proposed here:

1. Remove SDG
2. Remove Flows
3. Add PipelineContext

2 and 3 have merged already

1 is at instructlab/sdg#64

**Comment by hickeyma** [comment]
@shivchander Do you mind reviewing this and providing your feedback? This would be great as you had a lot of input in https://github.com/instructlab/sdg/issues/61 and with removing it in https://github.com/instructlab/sdg/issues/61#issuecomment-2205460470

**Pull request merged**
