### PR TITLE
Update spelling per #105

### PR DESCRIPTION
**Pull request by jjasghar**
PR #105 needs some new words added to the spelling dictionary.

### CODE REVIEW

**Review by markstur — CHANGES_REQUESTED** [review]
Knowlege and butvis are both typos so let's not add those

Also... YIKES!...  a re-sort regarding order of uppercase vs lower happened and so this PR is a big re-sort again.  Not good.  Let's not go back and forth on that.  PR should be simple additions and if we need to fix the sort again let's do that in a commit whichever order is preferred(?).

**Comment by jjasghar** [comment]
i just used `:<,'>sort` 😭 

I'm assuming that would be this would be the same with `sort` too right?

**Comment by markstur** [comment]
> i just used `:<,'>sort` 😭
> 
> I'm assuming that would be this would be the same with `sort` too right?

`:%sort i` would be case-insensitive to keep the current a's with A's, bees with Bees.  🐝 

add a u for bonus removal of dups.
I don't really have a preference (okay maybe case-insensitive) but don't like it thrashing back and forth

**Comment by jjasghar** [comment]
OK, i got it fixed :)

**Review by markstur — APPROVED** [review]
such a pretty diff, thanks!

Sorry for the extra work.  I'm thinking maybe I should not have allowed the last re-sort so you kind of paid the price on this one.

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
