### PR TITLE
New repository proposal: sdg

### PR DESCRIPTION
**Pull request by russellb**
This document includes a proposal for a new repository which contains
a Python library focused on Synthetic Data Generation (SDG). This is a
discreet area of functionality that can evolve on its own with its own
group of contributors and maintainers.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
Thanks!

**Review by khaledsulayman — APPROVED** [review]

**Review by nathan-weinberg — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
@russellb Can we add a bit about creating a new SDG Triager/Maintainer team, in line with the scheme we have for the CLI teams? These team will be responsible for triaging, maintenance, releases, etc.

Alternatively this can be a proposal to the `community` repo `CONTRIBUTORING_ROLES.md` doc once the new repo is created.

**Comment by markstur** [comment]
I wonder if anyone can come up with a less cryptic name than SDG, but I don't have a good suggestion (data-gen or synth-data... etc don't thrill me)

**Review by markstur — APPROVED** [review]
make it so

**Comment by lhawthorn** [comment]
Dumb question - why don't we just call it synthetic-data-generation? It does what it says on the tin.

**Comment by nathan-weinberg** [comment]
Honestly I'm not opposed to @lhawthorn's suggestion or something like `synthetic-datagen`

**Comment by russellb** [comment]
I would prefer a rough mapping to the Python package included in the repo. This proposal was instructlab/sdg for the instructlab-sdg package. For the other name suggestions, a PyPI check to see if it can also be the Python package name would be good. It would also be helpful to know if the name suggestions are brainstorming or a “-1” for the proposed name. 

Naming is hard.

**Review by hickeyma — COMMENTED** [review]
Nice proposal, thanks @russellb.

One thing should we also include the basic implementation (which is a modified version of self-instruct (https://arxiv.org/abs/2212.10560)) currently in the CLI to be moved to the repository also? That way we extract all SDG implementation from the CLI and we have the community supported implementations in 1 repository.

**Comment by bjhargrave** [comment]
> big +1 to moving away from git submodules for the schema - a package on pypi makes sense to me



> +1 to this as well

OK, I'll start some work towards this end.

**Comment by russellb** [comment]
https://github.com/instructlab/sdg

**Pull request merged**
